# Pandas

In [1]:
import pandas as pd

In [2]:
list1=[1,2,3,4,5]

In [3]:
list1

[1, 2, 3, 4, 5]

In [4]:
pd.Series(list1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
list2=['a','b','c','d','e']

In [6]:
list2

['a', 'b', 'c', 'd', 'e']

In [7]:
pd.Series(list2)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [10]:
pd.Series(data =list1 , index =list2)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
pd.Series(data = list2 , index= list1)

1    a
2    b
3    c
4    d
5    e
dtype: object

In [12]:
# Dataframe is a collection of rows and cols, it is just like table

# Numpy

In [13]:
import numpy as np

In [14]:
#import random nos from numpy library from standard normal distribution

In [15]:
#use randn function for this

In [22]:
import numpy as np

In [23]:
from numpy.random import randn

In [24]:
randn(5,4)

array([[-0.23665744, -0.51107745,  0.31710505, -0.07499477],
       [-0.92524771,  2.00696015, -0.35126171,  0.4245588 ],
       [-0.14625457, -1.27433301, -1.13047044,  1.71122494],
       [ 0.7890252 , -0.16178779,  1.18263668,  1.03739618],
       [-0.13240543,  1.18338837,  0.88365299,  0.3362002 ]])

In [25]:
# randn(5,4) means give it gives random values with 5 rows and 4 columns

In [26]:
randn(5,4)

array([[ 0.96628254,  0.87063215,  1.14990958,  0.20893949],
       [-1.48464572, -0.47934373, -0.75305801, -0.20675959],
       [-0.3067181 , -0.45468971,  2.22253687,  1.61496411],
       [ 0.47857233,  0.58276478, -0.01484487,  2.55972178],
       [-0.33078018, -0.66058998, -0.01870605,  0.17230936]])

In [27]:
# here we executed same code but new values appear everytime we execute

In [28]:
# if we want to fix values use seed

In [29]:
from numpy.random import randn
np.random.seed(101)
randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [30]:
randn(5,4)

array([[ 0.30266545,  1.69372293, -1.70608593, -1.15911942],
       [-0.13484072,  0.39052784,  0.16690464,  0.18450186],
       [ 0.80770591,  0.07295968,  0.63878701,  0.3296463 ],
       [-0.49710402, -0.7540697 , -0.9434064 ,  0.48475165],
       [-0.11677332,  1.9017548 ,  0.23812696,  1.99665229]])

In [31]:
from numpy.random import randn
np.random.seed(101)
randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [34]:
from numpy.random import randn
np.random.seed(101)
df =pd.DataFrame(randn(5,4), index= 'A B C D E'.split() , columns ='X Y W Z'.split())

In [35]:
df

X         Y         W         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
df['W']

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: W, dtype: float64

In [38]:
df['new']= df['X'] + df['Y']

In [39]:
df['new']

A    3.334983
B    0.331800
C   -1.278046
D   -0.570177
E    2.169552
Name: new, dtype: float64

In [40]:
df

X         Y         W         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [42]:
df.drop('new', axis=1)

X         Y         W         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [43]:
df

X         Y         W         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [47]:
# drop will not permanently delete the new column, also axis is equal to 1 means full column, if 0 then it means row of that new col

In [46]:
#to permenantly delete any columns use inplace,  

In [48]:
df.drop('new', axis=1, inplace= True)

In [50]:
df

X         Y         W         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [51]:
import numpy as np

In [52]:
list3=[1,2,3,4]

In [53]:
type(list3)

list

In [54]:
np.array(list3)

array([1, 2, 3, 4])

In [55]:
#here we converted the list into array

In [56]:
list4=[[1,2,3],[22,33,44],[66,77,88]]
np.array(list4)

array([[ 1,  2,  3],
       [22, 33, 44],
       [66, 77, 88]])

In [57]:
#here we converted a nested list into array /matrix

In [58]:
type(list4)

list

In [59]:
list4

[[1, 2, 3], [22, 33, 44], [66, 77, 88]]

In [60]:
np.array(list4)

array([[ 1,  2,  3],
       [22, 33, 44],
       [66, 77, 88]])

In [61]:
type(np.array(list4))

numpy.ndarray

In [63]:
list4=np.array(list4)

In [64]:
list4

array([[ 1,  2,  3],
       [22, 33, 44],
       [66, 77, 88]])

In [65]:
list4.ndim

2

In [66]:
#here n means 2 rows and 2 columns in above array

In [67]:
list4.shape

(3, 3)

In [68]:
# here 3 rows and 3 columns

# range function

In [69]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [70]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
#here the above function  is "a range" function, here we give strt and end values 

In [72]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [73]:
# here 3 is step size , that means after first values it will leave 3 values in between 

In [74]:
#generate arrays of zeros and ones

In [75]:
import numpy as np

In [77]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
a=np.zeros((5,5))

In [79]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
a.shape

(5, 5)

In [81]:
np.ones(4)

array([1., 1., 1., 1.])

In [83]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [84]:
b=np.ones((4,4))

In [85]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
#linespace - genearte nos with equal spaced intervals

In [87]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [88]:
#eye - identity matrix

In [89]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
#gen random nos using randn function

In [92]:
np.random.rand(5,5)

array([[0.94926413, 0.47816742, 0.46111934, 0.63728903, 0.324608  ],
       [0.11757809, 0.051101  , 0.63765865, 0.81226589, 0.67026042],
       [0.6517677 , 0.42456894, 0.65659534, 0.2091615 , 0.65992452],
       [0.5296234 , 0.74852037, 0.09375686, 0.78452185, 0.68724204],
       [0.6950785 , 0.49686652, 0.97536113, 0.20352762, 0.29902041]])

In [93]:
a=np.random.rand(5,5)

In [94]:
a.ndim

2

In [95]:
np.random.randn(5)

array([-0.1565979 , -0.85519604,  1.54199041,  0.66631932, -0.53823463])

In [96]:
np.random.randn(5,5)

array([[-0.56858136,  1.40733825,  0.64180551, -0.9050999 , -0.39115663],
       [ 1.02829316, -1.9726051 , -0.86688504,  0.7207876 , -1.22308204],
       [ 1.60677986, -1.11570997, -1.38537856, -1.32966006,  0.04145994],
       [-0.4110554 , -0.7713286 ,  0.11047741, -0.80465151,  0.25354804],
       [ 0.64914775,  0.35894053, -1.08047146,  0.90239776,  0.16178119]])

In [97]:
#randint

In [98]:
np.random.randint(100)

35

In [99]:
np.random.randint(100)

25

In [100]:
#here random integars are displayed in range upto 100

In [102]:
np.random.randint(1,100,200)

array([96, 76, 73, 12, 77, 80, 51, 23, 60, 67,  2, 35, 38, 58, 36, 43, 45,
       50, 32, 80, 86,  4, 56, 74, 94, 95, 41, 55, 89, 95, 87, 18, 69, 18,
       19, 61, 84, 83,  8, 68, 35, 77, 95, 21, 70, 74, 60, 35, 70, 26, 79,
       93, 75, 76, 34, 10, 44, 21, 83, 31,  4, 47, 30, 48, 28, 82, 72, 26,
       95, 58, 22, 30,  7, 55, 48, 48, 61,  7, 76, 98, 54, 45, 99, 40, 33,
       88, 79, 22, 91, 15, 21,  2, 71, 26, 46, 97, 33, 32, 42, 80, 88, 23,
       95, 47, 72, 25, 42, 37, 32, 17, 88, 23, 97,  4, 13, 72, 10, 88, 96,
       40, 65, 63, 89, 77, 94, 84, 96, 69, 70, 60, 53,  8, 41, 74, 87, 15,
       50, 98, 26, 58, 41, 18, 33, 84, 98, 28, 48, 14, 71, 16, 93, 19, 95,
       49, 66, 83, 35,  6, 47, 84, 28, 27, 21, 88, 85, 18, 60, 65, 45,  5,
       52, 50, 75, 83, 38, 54, 94, 74,  6, 38, 57, 36, 16, 41, 43, 72, 38,
       47, 72, 92, 98, 37, 44, 28, 67, 58,  4, 56, 71, 42])

In [103]:
#here array displays random nos(duplicate also) ranges from 1 to 100 and it has 200 values

In [104]:
np.random.randint(1,100)

68

# array attributes and methods

In [107]:
#arr

In [110]:
arr = np.arange(25)

In [111]:
#here we have used " a range"  

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [113]:
np.random.randint(1,100,25)

array([73, 89, 68, 76, 70, 93, 21, 16, 58, 10, 70, 98, 92, 52, 55, 46, 39,
       16, 43, 62,  9,  4, 89, 73, 42])

In [114]:
np.random.randint(1,25,10)

array([20, 12, 17,  6, 11,  3, 19,  3, 15, 15])

In [115]:
#here this displays random integers in array from 1 to 25  ,total 10 values

In [116]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [117]:
# RESHAPE

In [118]:
type(arr)

numpy.ndarray

# max min, argmax argmin

In [123]:
arr1=np.random.randint(1,30,5)

In [124]:
arr1

array([22, 15, 15, 28,  5])

In [125]:
arr1.min()

5

In [126]:
arr1.argmin()

4

In [127]:
#here argmin() gives index value, whereas min() gives value

In [128]:
arr1.max()

28

In [129]:
arr1.argmax()

3

In [130]:
arr1.shape

(5,)

In [132]:
arr1.reshape(1,5)

array([[22, 15, 15, 28,  5]])

In [133]:
arr2=arr1.reshape(1,5)

In [134]:
arr2

array([[22, 15, 15, 28,  5]])

In [135]:
arr2.shape

(1, 5)

In [136]:
arr2.reshape(5,1)

array([[22],
       [15],
       [15],
       [28],
       [ 5]])

In [140]:
arr1

array([22, 15, 15, 28,  5])

In [141]:
arr1[2]

15

In [142]:
arr1[1:4]

array([15, 15, 28])

In [143]:
arr1[:]

array([22, 15, 15, 28,  5])

In [144]:
#here we did bracket indexing from array

# broadcasting

In [145]:
#setting a fixed vlue for a particular range in an array

In [146]:
arr1[1:4]=500

In [147]:
arr1

array([ 22, 500, 500, 500,   5])

In [161]:
arr1[0:3]

array([99, 99, 99])

In [158]:
arr1[:]=99

array([99, 99, 99])

In [151]:
arr1

array([99, 99, 99, 99, 99])

In [152]:
#note chnges occure in original array

In [162]:
#use .copy to store values

In [163]:
arrcopy=arr1.copy()

In [164]:
arrcopy

array([99, 99, 99, 99, 99])

# array 2d indexing

In [165]:
arr2d=np.array([[20,12,4],[20,45,67],[43,89,60]])

In [166]:
arr2d

array([[20, 12,  4],
       [20, 45, 67],
       [43, 89, 60]])

In [167]:
arr2d[1]

array([20, 45, 67])

In [168]:
arr2d[1][2]

67

In [169]:
#we are indexing row 1 and in that 2nd element

In [174]:
arr2d[:2,1:]

array([[12,  4],
       [45, 67]])

In [172]:
#here :2 means strt from begingining upto 2nd row (0 to 2 range means oth row and 1st row eliminte 2nd row)

In [175]:
#here 1: means strt from 1st column and end with last column( 1 tp last means from 0 column will eliminate )

In [176]:
arr2d[:2,0:]

array([[20, 12,  4],
       [20, 45, 67]])

In [179]:
arr2d[:3,2:]

array([[ 4],
       [67],
       [60]])

In [180]:
arr2d[2]

array([43, 89, 60])

In [181]:
arr2d[2,:]

array([43, 89, 60])

# fancy indexing

In [186]:
arr_2d=np.zeros((10,10))

In [187]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [189]:
arr_2d.shape[1]

10

In [191]:
length_arr=arr_2d.shape[1]

In [192]:
length_arr

10

In [194]:
for i in range(length_arr):
    arr_2d[i]=i

In [195]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [196]:
arr_2d[[2,6,4]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [197]:
arr_2d[[1,0,8]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [200]:
arr3=np.arange(0,10)

In [201]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
arr3 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [203]:
bool_arr3=arr3 > 4

In [204]:
bool_arr3

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [207]:
arr3[bool_arr3]

array([5, 6, 7, 8, 9])

In [208]:
arr3[arr3>2]

array([3, 4, 5, 6, 7, 8, 9])

In [209]:
x=5
arr3[arr3>x]

array([6, 7, 8, 9])

# Performing Hstack and Vstack

In [7]:
import numpy as np
a= np.array([1,2,3])
b= np.array([4,5,6])

print("a : {}".format(a))
print("dimension of a :" , a.ndim)

print("b : {}".format(b))
print("dimension of b :" , b.ndim)

a : [1 2 3]
dimension of a : 1
b : [4 5 6]
dimension of b : 1


In [8]:
c = np.hstack((a,b))

print("c : {}".format(c))
print("dimension of c :" , c.ndim)

c : [1 2 3 4 5 6]
dimension of c : 1


In [9]:
d = np.vstack((a,b))

print("d : {}".format(d))
print("dimension of d :" , d.ndim)

d : [[1 2 3]
 [4 5 6]]
dimension of d : 2


In [10]:
# hstack join horizontly and Vstack joins vertically

# Concatenation numpy

In [11]:
# when axis =0 then both concatenationg arrays , should have same no. of columns( think like adding new row)

In [12]:
# when axis =1 then both concatenationg arrays , should have same no. of rows( think like adding new column)

In [13]:
a = [[1,2], [4,5]]
A= np.array(a)
print(A)
print(A.shape)

[[1 2]
 [4 5]]
(2, 2)


In [14]:
b = [[9,7]]
B= np.array(b)
print(B)
print(B.shape)

[[9 7]]
(1, 2)


In [15]:
#LETS CONCATENATE A & B

In [17]:
C = np.concatenate((A,B), axis =0 )
print(C)
print(C.shape)

[[1 2]
 [4 5]
 [9 7]]
(3, 2)


In [18]:
# when same no. of columns we have to use axis =0

In [19]:
# when we try to add two arrays with diff rows and axis=1 we will get error
# when we try to add two arrays with diff columns and axis=0 we will get error

# searching in numpy

# np.where()

In [21]:
# syntax  np.where(condition,array,replacement)

In [23]:
a=[1,2,3,4,5,6,6]
A= np.array(a)
print(A)

[1 2 3 4 5 6 6]


# task1  replace all odd nos with -1

In [24]:
B= np.where( A % 2 ==0 , A ,-1)
print(B)

[-1  2 -1  4 -1  6  6]


# task 2 replace all the nos less than 0 with 45

In [26]:
c=[--1,-2,40,23,45,-4,-5,0,-2,-4,-9]
C= np.array(c)
print(C)

[ 1 -2 40 23 45 -4 -5  0 -2 -4 -9]


In [29]:
D = np.where( C>0, C, 45)
print(D)

[ 1 45 40 23 45 45 45 45 45 45 45]
